cloud:
  aws:
    credentials:
      access-key: AKIA2Y7K6IMXO25WN3PK
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: rozzz-blog-storage

#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB

server:
  port: 8080
